import { useState } from "react";
import type { Project } from "@forge/shared";
import { buildProject, createProject } from "./api.js";
import { EntityPanel } from "./EntityPanel.js";

type View = "home" | "spec" | "preview";

export default function App() {
  const [view, setView] = useState<View>("home");
  const [description, setDescription] = useState("");
  const [project, setProject] = useState<Project | null>(null);
  const [providerName, setProviderName] = useState<string>("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeEntity, setActiveEntity] = useState<string | null>(null);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<string, string>>({});

  async function handleDescribe(e: React.FormEvent) {
    e.preventDefault();
    if (!description.trim()) return;
    setBusy(true);
    setError(null);
    try {
      const { project, providerName } = await createProject(description);
      setProject(project);
      setProviderName(providerName);
      setView("spec");
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setBusy(false);
    }
  }

  async function handleBuild() {
    if (!project) return;
    setBusy(true);
    setError(null);
    try {
      const { project: built } = await buildProject(project.id);
      setProject(built);
      setActiveEntity(built.spec.entities[0]?.name ?? null);
      setView("preview");
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="app">
      <header className="topbar">
        <span className="brand">Forge AI</span>
        <span className="tagline">Describe your business. Get your software company.</span>
      </header>

      {error && <p className="error banner">{error}</p>}

      {view === "home" && (
        <main className="home">
          <h1>What do you want to build?</h1>
          <form onSubmit={handleDescribe}>
            <textarea
              rows={5}
              placeholder="e.g. Build an appointment-management application for a beauty clinic. I need customers, appointments, employees, services, an admin dashboard and automatic appointment status tracking."
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
            <button type="submit" disabled={busy}>
              {busy ? "Understanding your business…" : "Describe it"}
            </button>
          </form>
          <p className="muted small">
            Phase 1 slice: this generates a real product spec and a real, working generic CRUD
            application (schema + API + UI) — not a mockup. See the README for what's on the
            roadmap next (custom generated codebases, auth, deployment, multi-agent builds).
          </p>
        </main>
      )}

      {view === "spec" && project && (
        <main className="spec-review">
          <h1>What I understood</h1>
          <p className="provider-tag">Generated by: {providerName} provider</p>
          <p>{project.spec.summary}</p>

          <section>
            <h2>Roles</h2>
            <div className="chips">
              {project.spec.roles.map((r) => (
                <span className="chip" key={r}>
                  {r}
                </span>
              ))}
            </div>
          </section>

          <section>
            <h2>Entities</h2>
            {project.spec.entities.map((entity) => (
              <div key={entity.name} className="entity-summary">
                <strong>{entity.name}</strong>
                <span className="muted">
                  {" "}
                  — {entity.fields.map((f) => f.name).join(", ")}
                </span>
              </div>
            ))}
          </section>

          <section>
            <h2>Assumptions I'm making</h2>
            <ul>
              {project.spec.assumptions.map((a, i) => (
                <li key={i}>{a}</li>
              ))}
            </ul>
          </section>

          {project.spec.openQuestions.length > 0 && (
            <section>
              <h2>Decisions I need from you</h2>
              {project.spec.openQuestions.map((q, i) => (
                <div key={i} className="open-question">
                  <p>{q.question}</p>
                  <div className="chips">
                    {q.options.map((opt) => (
                      <button
                        type="button"
                        key={opt}
                        className={selectedAnswers[q.question] === opt ? "chip chip-selected" : "chip chip-button"}
                        onClick={() => setSelectedAnswers((prev) => ({ ...prev, [q.question]: opt }))}
                      >
                        {opt}
                      </button>
                    ))}
                  </div>
                  <p className="muted small">
                    Recorded for this session only — Phase 1 doesn't yet feed this back into the
                    generated schema. Recommendation: {q.recommendation ?? "no default"}.
                  </p>
                </div>
              ))}
            </section>
          )}

          <button type="button" onClick={handleBuild} disabled={busy}>
            {busy ? "Building…" : "Build App"}
          </button>
        </main>
      )}

      {view === "preview" && project && (
        <main className="preview">
          <h1>{project.name}</h1>
          <nav className="entity-tabs">
            {project.spec.entities.map((entity) => (
              <button
                key={entity.name}
                className={activeEntity === entity.name ? "tab tab-active" : "tab"}
                onClick={() => setActiveEntity(entity.name)}
              >
                {entity.name}
              </button>
            ))}
          </nav>
          {project.spec.entities
            .filter((e) => e.name === activeEntity)
            .map((entity) => <EntityPanel key={entity.name} projectId={project.id} entity={entity} />)}
        </main>
      )}
    </div>
  );
}
