import { useEffect, useState } from "react";
import type { Project, User } from "@forge/shared";
import { clearToken, createProject, getToken, logout, me, streamBuild, streamRefine } from "./api.js";
import { AuthScreen } from "./AuthScreen.js";
import { BuildProgress } from "./BuildProgress.js";
import { EntityPanel } from "./EntityPanel.js";
import { HistoryPanel } from "./HistoryPanel.js";

type View = "home" | "spec" | "building" | "preview";

export default function App() {
  const [user, setUser] = useState<User | null>(null);
  const [checkingSession, setCheckingSession] = useState(true);
  const [view, setView] = useState<View>("home");
  const [description, setDescription] = useState("");
  const [project, setProject] = useState<Project | null>(null);
  const [providerName, setProviderName] = useState<string>("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeEntity, setActiveEntity] = useState<string | null>(null);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<string, string>>({});
  const [refineText, setRefineText] = useState("");
  const [showHistory, setShowHistory] = useState(false);
  const [buildMode, setBuildMode] = useState<"build" | "refine">("build");

  useEffect(() => {
    if (!getToken()) {
      setCheckingSession(false);
      return;
    }
    me()
      .then(({ user }) => setUser(user))
      .catch(() => clearToken())
      .finally(() => setCheckingSession(false));
  }, []);

  if (checkingSession) {
    return (
      <div className="app">
        <p className="muted">Loading…</p>
      </div>
    );
  }

  if (!user) {
    return <AuthScreen onAuthenticated={setUser} />;
  }

  async function handleDescribe(e: React.FormEvent) {
    e.preventDefault();
    if (!description.trim()) return;
    setBusy(true);
    setError(null);
    try {
      const { project, providerName } = await createProject(description);
      setProject(project);
      setProviderName(providerName);
      setView("spec");
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setBusy(false);
    }
  }

  function handleBuild() {
    setBuildMode("build");
    setView("building");
  }

  function handleRefine(e: React.FormEvent) {
    e.preventDefault();
    if (!refineText.trim()) return;
    setBuildMode("refine");
    setView("building");
  }

  function handleBuildComplete(builtProject: Project) {
    setProject(builtProject);
    setActiveEntity((prev) => prev ?? builtProject.spec.entities[0]?.name ?? null);
    setRefineText("");
    setView("preview");
  }

  async function handleLogout() {
    await logout();
    setUser(null);
    setProject(null);
    setView("home");
  }

  return (
    <div className="app">
      <header className="topbar">
        <div>
          <span className="brand">Forge AI</span>
          <span className="tagline">Describe your business. Get your software company.</span>
        </div>
        <div className="topbar-right">
          <span className="muted small">{user.email}</span>
          <button type="button" className="secondary" onClick={handleLogout}>
            Log out
          </button>
        </div>
      </header>

      {error && <p className="error banner">{error}</p>}

      {view === "home" && (
        <main className="home">
          <h1>What do you want to build?</h1>
          <form onSubmit={handleDescribe}>
            <textarea
              rows={5}
              placeholder="e.g. Build an appointment-management application for a beauty clinic. I need customers, appointments, employees, services, an admin dashboard and automatic appointment status tracking."
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
            <button type="submit" disabled={busy}>
              {busy ? "Understanding your business…" : "Describe it"}
            </button>
          </form>
          <p className="muted small">
            Phase 1+ slice: this generates a real product spec and a real, working generic CRUD
            application (schema + API + UI), built by a real multi-step agent pipeline you can
            watch run. See the README for what's still on the roadmap (custom generated codebases,
            deployment).
          </p>
        </main>
      )}

      {view === "spec" && project && (
        <main className="spec-review">
          <h1>What I understood</h1>
          <p className="provider-tag">Generated by: {providerName} provider</p>
          <p>{project.spec.summary}</p>

          <section>
            <h2>Roles</h2>
            <div className="chips">
              {project.spec.roles.map((r) => (
                <span className="chip" key={r}>
                  {r}
                </span>
              ))}
            </div>
          </section>

          <section>
            <h2>Entities</h2>
            {project.spec.entities.map((entity) => (
              <div key={entity.name} className="entity-summary">
                <strong>{entity.name}</strong>
                <span className="muted"> — {entity.fields.map((f) => f.name).join(", ")}</span>
              </div>
            ))}
          </section>

          <section>
            <h2>Assumptions I'm making</h2>
            <ul>
              {project.spec.assumptions.map((a, i) => (
                <li key={i}>{a}</li>
              ))}
            </ul>
          </section>

          {project.spec.openQuestions.length > 0 && (
            <section>
              <h2>Decisions I need from you</h2>
              {project.spec.openQuestions.map((q, i) => (
                <div key={i} className="open-question">
                  <p>{q.question}</p>
                  <div className="chips">
                    {q.options.map((opt) => (
                      <button
                        type="button"
                        key={opt}
                        className={selectedAnswers[q.question] === opt ? "chip chip-selected" : "chip chip-button"}
                        onClick={() => setSelectedAnswers((prev) => ({ ...prev, [q.question]: opt }))}
                      >
                        {opt}
                      </button>
                    ))}
                  </div>
                  <p className="muted small">
                    Recorded for this session only — Phase 1 doesn't yet feed this back into the
                    generated schema. Recommendation: {q.recommendation ?? "no default"}.
                  </p>
                </div>
              ))}
            </section>
          )}

          <button type="button" onClick={handleBuild}>
            Build App
          </button>
        </main>
      )}

      {view === "building" && project && (
        <BuildProgress
          title={buildMode === "build" ? "AI Team — Building your app" : "AI Team — Applying your change"}
          run={(onEvent) =>
            buildMode === "build" ? streamBuild(project.id, onEvent) : streamRefine(project.id, refineText, onEvent)
          }
          onComplete={handleBuildComplete}
          onBack={() => setView(buildMode === "build" ? "spec" : "preview")}
        />
      )}

      {view === "preview" && project && (
        <main className="preview">
          <div className="preview-header">
            <h1>{project.name}</h1>
            <button type="button" className="secondary" onClick={() => setShowHistory(true)}>
              Time Machine
            </button>
          </div>

          <form className="refine-box" onSubmit={handleRefine}>
            <input
              type="text"
              placeholder="Describe a change, e.g. “Also track invoices for customers”"
              value={refineText}
              onChange={(e) => setRefineText(e.target.value)}
            />
            <button type="submit" disabled={!refineText.trim()}>
              Improve this app
            </button>
          </form>

          <nav className="entity-tabs">
            {project.spec.entities.map((entity) => (
              <button
                key={entity.name}
                className={activeEntity === entity.name ? "tab tab-active" : "tab"}
                onClick={() => setActiveEntity(entity.name)}
              >
                {entity.name}
              </button>
            ))}
          </nav>
          {project.spec.entities
            .filter((e) => e.name === activeEntity)
            .map((entity) => <EntityPanel key={entity.name} projectId={project.id} entity={entity} />)}

          {showHistory && (
            <HistoryPanel
              projectId={project.id}
              onClose={() => setShowHistory(false)}
              onRestored={(restored) => {
                setProject(restored);
                setActiveEntity(restored.spec.entities[0]?.name ?? null);
                setShowHistory(false);
              }}
            />
          )}
        </main>
      )}
    </div>
  );
}
