import type { Project } from "@forge/shared";

/**
 * Generates a real, standalone Express + SQLite + vanilla-JS application
 * from a project's ProductSpec. This is the "own your code" export: the
 * output has zero dependency on Forge AI at runtime — no import of our
 * packages, no network call back to this platform. It's a small,
 * intentionally readable app (one server file, one HTML file) rather than
 * a framework-heavy scaffold, so someone can actually open and understand
 * it. See docs/ADR/0003-code-export.md for why it's shaped this way.
 */

const SAFE_IDENTIFIER = /^[A-Za-z][A-Za-z0-9_]*$/;

function assertSafe(name: string, kind: string): string {
  if (!SAFE_IDENTIFIER.test(name)) {
    throw new Error(`Refusing to export: unsafe ${kind} identifier "${name}"`);
  }
  return name;
}

function packageName(projectName: string): string {
  const slug = projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug || "forge-exported-app";
}

function renderPackageJson(project: Project): string {
  return JSON.stringify(
    {
      name: packageName(project.name),
      private: true,
      version: "1.0.0",
      description: `Exported from Forge AI: ${project.description}`.slice(0, 200),
      type: "module",
      scripts: {
        start: "node server.js",
      },
      dependencies: {
        express: "^4.21.1",
      },
      engines: {
        node: ">=22.5.0",
      },
    },
    null,
    2,
  );
}

function renderReadme(project: Project): string {
  const entityList = project.spec.entities.map((e) => `- **${e.label ?? e.name}** (\`${e.name}\`)`).join("\n");
  return `# ${project.name}

Exported from Forge AI. This is a complete, standalone application —
running it never talks back to Forge AI, and there is nothing else to
install beyond what's in \`package.json\`.

## What this is

${project.description}

## Entities

${entityList}

## Running it

\`\`\`bash
npm install
npm start
\`\`\`

Open http://localhost:3000. Data is stored in \`data.sqlite\` next to
\`server.js\` (created automatically on first run).

## What's here

- \`server.js\` — the entire backend: creates the SQLite schema for every
  entity above and exposes a REST API at \`/api/<Entity>\` (GET list, POST
  create, PATCH update, DELETE) with the same validation rules (required
  fields, enum membership) the Forge AI preview enforced.
- \`public/index.html\` — the entire frontend: one file, no build step, no
  framework. Reads \`/api/entities\` for field metadata and renders a tab +
  table + form per entity.
- \`data.sqlite\` — your data. Back it up like any file.

## Extending it

There's no magic here — read \`server.js\` top to bottom, it's a few
hundred lines. Common next steps: swap SQLite for Postgres (replace the
\`node:sqlite\` calls), add authentication (there is none in this export —
see Forge AI's own auth in \`apps/api/src/auth/\` for a reference), or add
real fields by editing the \`ENTITIES\` array at the top of \`server.js\` and
restarting (existing columns are kept; SQLite needs \`ALTER TABLE\` for new
ones, same as Forge AI's own migration engine does).
`;
}

function renderServerJs(project: Project): string {
  for (const entity of project.spec.entities) {
    assertSafe(entity.name, "entity");
    for (const field of entity.fields) {
      assertSafe(field.name, "field");
    }
  }

  const entitiesJson = JSON.stringify(
    project.spec.entities.map((e) => ({
      name: e.name,
      label: e.label ?? e.name,
      fields: e.fields.map((f) => ({
        name: f.name,
        label: f.label ?? f.name,
        type: f.type,
        required: !!f.required,
        enumValues: f.enumValues ?? null,
        enumLabels: f.enumLabels ?? null,
      })),
    })),
    null,
    2,
  );

  return `// Generated by Forge AI — this file has no dependency on Forge AI at
// runtime. It's yours: read it, edit it, deploy it anywhere Node runs.
import express from "express";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { DatabaseSync } from "node:sqlite";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const db = new DatabaseSync(path.join(__dirname, "data.sqlite"));

const ENTITIES = ${entitiesJson};

const SAFE_IDENTIFIER = /^[A-Za-z][A-Za-z0-9_]*$/;
function assertSafe(name) {
  if (!SAFE_IDENTIFIER.test(name)) throw new Error(\`Unsafe identifier: \${name}\`);
  return name;
}

function sqlType(type) {
  if (type === "number" || type === "relation") return type === "relation" ? "INTEGER" : "REAL";
  if (type === "boolean") return "INTEGER";
  return "TEXT";
}

for (const entity of ENTITIES) {
  assertSafe(entity.name);
  const columns = ["id INTEGER PRIMARY KEY AUTOINCREMENT", "createdAt TEXT NOT NULL"];
  for (const field of entity.fields) {
    assertSafe(field.name);
    columns.push(\`\${field.name} \${sqlType(field.type)}\${field.required ? " NOT NULL" : ""}\`);
  }
  db.exec(\`CREATE TABLE IF NOT EXISTS \${entity.name} (\${columns.join(", ")})\`);
}

function coerce(field, value) {
  if (value === undefined || value === null || value === "") {
    if (field.required) throw new Error(\`Field "\${field.name}" is required\`);
    return null;
  }
  if (field.type === "number" || field.type === "relation") {
    const n = Number(value);
    if (Number.isNaN(n)) throw new Error(\`Field "\${field.name}" must be a number\`);
    return n;
  }
  if (field.type === "boolean") return value === true || value === "true" || value === 1 || value === "1" ? 1 : 0;
  if (field.type === "enum") {
    if (field.enumValues && !field.enumValues.includes(String(value))) {
      throw new Error(\`Field "\${field.name}" must be one of: \${field.enumValues.join(", ")}\`);
    }
    return String(value);
  }
  return String(value);
}

function rowToRecord(entity, row) {
  const record = { id: row.id, createdAt: row.createdAt };
  for (const field of entity.fields) {
    record[field.name] = field.type === "boolean" ? Boolean(row[field.name]) : row[field.name];
  }
  return record;
}

const app = express();
app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));

app.get("/api/entities", (_req, res) => res.json({ entities: ENTITIES }));

for (const entity of ENTITIES) {
  const base = \`/api/\${entity.name}\`;
  const columns = entity.fields.map((f) => f.name);

  app.get(base, (_req, res) => {
    const rows = db.prepare(\`SELECT * FROM \${entity.name} ORDER BY id DESC\`).all();
    res.json({ records: rows.map((r) => rowToRecord(entity, r)) });
  });

  app.post(base, (req, res) => {
    try {
      const values = entity.fields.map((f) => coerce(f, req.body?.[f.name]));
      const createdAt = new Date().toISOString();
      const placeholders = ["?", ...columns.map(() => "?")].join(", ");
      const stmt = db.prepare(\`INSERT INTO \${entity.name} (createdAt, \${columns.join(", ")}) VALUES (\${placeholders})\`);
      const result = stmt.run(createdAt, ...values);
      const row = db.prepare(\`SELECT * FROM \${entity.name} WHERE id = ?\`).get(result.lastInsertRowid);
      res.status(201).json({ record: rowToRecord(entity, row) });
    } catch (err) {
      res.status(400).json({ error: err.message });
    }
  });

  app.patch(\`\${base}/:id\`, (req, res) => {
    try {
      const existing = db.prepare(\`SELECT * FROM \${entity.name} WHERE id = ?\`).get(req.params.id);
      if (!existing) return res.status(404).json({ error: "Not found" });
      const merged = { ...existing, ...req.body };
      const values = entity.fields.map((f) => coerce(f, merged[f.name]));
      db.prepare(\`UPDATE \${entity.name} SET \${columns.map((c) => \`\${c} = ?\`).join(", ")} WHERE id = ?\`).run(...values, req.params.id);
      const row = db.prepare(\`SELECT * FROM \${entity.name} WHERE id = ?\`).get(req.params.id);
      res.json({ record: rowToRecord(entity, row) });
    } catch (err) {
      res.status(400).json({ error: err.message });
    }
  });

  app.delete(\`\${base}/:id\`, (req, res) => {
    const result = db.prepare(\`DELETE FROM \${entity.name} WHERE id = ?\`).run(req.params.id);
    if (result.changes === 0) return res.status(404).json({ error: "Not found" });
    res.status(204).end();
  });
}

const port = process.env.PORT || 3000;
app.listen(port, () => console.log(\`\${${JSON.stringify(project.name)}} running at http://localhost:\${port}\`));
`;
}

function isHebrew(text: string): boolean {
  return /[֐-׿]/.test(text);
}

function renderIndexHtml(project: Project): string {
  const hebrew = project.spec.entities.some((e) => isHebrew(e.label ?? ""));
  const dir = hebrew ? "rtl" : "ltr";
  const lang = hebrew ? "he" : "en";
  const title = project.name.replace(/</g, "&lt;");

  return `<!doctype html>
<html lang="${lang}" dir="${dir}">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${title}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif; margin: 0; background: #f6f2ea; color: #241f19; }
  .app { max-width: 880px; margin: 0 auto; padding: 24px 16px 64px; }
  h1 { font-size: 26px; margin: 0 0 20px; }
  nav { display: flex; gap: 6px; flex-wrap: wrap; margin-bottom: 20px; }
  nav button { padding: 8px 16px; border-radius: 8px; border: 1px solid #e6ddcc; background: #fff; cursor: pointer; font: inherit; }
  nav button.active { background: #d9622b; color: #fff; border-color: #d9622b; }
  .panel { background: #fff; border: 1px solid #e6ddcc; border-radius: 14px; padding: 20px; box-shadow: 0 8px 24px rgba(36,31,25,0.08); }
  form.record-form { display: grid; grid-template-columns: repeat(auto-fill, minmax(140px, 1fr)); gap: 12px; margin-bottom: 16px; padding-bottom: 16px; border-bottom: 1px solid #efe8da; }
  .field { display: flex; flex-direction: column; gap: 4px; font-size: 12.5px; color: #83786a; min-width: 0; }
  input, select, textarea { font: inherit; padding: 8px 10px; border: 1px solid #e6ddcc; border-radius: 6px; width: 100%; }
  button[type="submit"], .btn { padding: 9px 18px; border-radius: 8px; border: none; background: #d9622b; color: #fff; font: inherit; font-weight: 600; cursor: pointer; }
  .table-scroll { overflow-x: auto; }
  table { width: 100%; border-collapse: collapse; font-size: 14px; }
  th, td { text-align: start; padding: 8px 10px; border-bottom: 1px solid #efe8da; white-space: nowrap; }
  .row-actions button { margin-inline-start: 4px; padding: 5px 10px; border-radius: 6px; border: 1px solid #e6ddcc; background: #fff; cursor: pointer; }
  .muted { color: #83786a; font-size: 13px; }
  .error { color: #c0392b; }
</style>
</head>
<body>
<div class="app">
  <h1>${title}</h1>
  <nav id="tabs"></nav>
  <div class="panel" id="panel"></div>
</div>
<script>
let ENTITIES = [];
let ACTIVE = null;
let EDITING_ID = null;

async function api(path, opts) {
  const res = await fetch("/api" + path, {
    ...opts,
    headers: { "content-type": "application/json", ...(opts && opts.headers) },
  });
  if (!res.ok) {
    const body = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(body.error || ("Request failed (" + res.status + ")"));
  }
  if (res.status === 204) return undefined;
  return res.json();
}

function emptyForm(entity) {
  const form = {};
  for (const f of entity.fields) form[f.name] = f.type === "boolean" ? false : "";
  return form;
}

function fieldInputHtml(entity, field, value) {
  const id = "f_" + entity.name + "_" + field.name;
  if (field.type === "boolean") {
    return '<input type="checkbox" id="' + id + '" ' + (value ? "checked" : "") + ' />';
  }
  if (field.type === "enum") {
    const opts = (field.enumValues || []).map((v) => {
      const label = (field.enumLabels && field.enumLabels[v]) || v;
      const sel = String(value) === v ? "selected" : "";
      return '<option value="' + v + '" ' + sel + '>' + label + '</option>';
    }).join("");
    return '<select id="' + id + '"><option value="" disabled ' + (value ? "" : "selected") + '>...</option>' + opts + '</select>';
  }
  if (field.type === "longtext") {
    return '<textarea id="' + id + '" rows="2">' + (value ?? "") + '</textarea>';
  }
  if (field.type === "date") {
    return '<input type="date" id="' + id + '" value="' + (value ?? "") + '" />';
  }
  if (field.type === "number" || field.type === "relation") {
    return '<input type="number" id="' + id + '" value="' + (value ?? "") + '" />';
  }
  const escaped = String(value ?? "").replace(/"/g, "&quot;");
  return '<input type="text" id="' + id + '" value="' + escaped + '" />';
}

function readForm(entity) {
  const data = {};
  for (const f of entity.fields) {
    const el = document.getElementById("f_" + entity.name + "_" + f.name);
    data[f.name] = f.type === "boolean" ? el.checked : el.value;
  }
  return data;
}

function formatCell(field, value) {
  if (value === null || value === undefined || value === "") return "—";
  if (field.type === "boolean") return value ? "Yes" : "No";
  if (field.type === "enum" && field.enumLabels && field.enumLabels[value]) return field.enumLabels[value];
  return String(value);
}

async function renderPanel(entity) {
  const panel = document.getElementById("panel");
  const formValues = emptyForm(entity);
  const fieldsHtml = entity.fields.map((f) =>
    '<label class="field"><span>' + f.label + (f.required ? " *" : "") + '</span>' + fieldInputHtml(entity, f, formValues[f.name]) + '</label>'
  ).join("");

  panel.innerHTML =
    '<h3>' + entity.label + '</h3>' +
    '<form class="record-form" id="record-form">' + fieldsHtml +
      '<div><button type="submit" class="btn" id="submit-btn">Add</button> <button type="button" id="cancel-btn" style="display:none">Cancel</button></div>' +
    '</form>' +
    '<p id="panel-error" class="error"></p>' +
    '<div id="table-holder"></div>';

  document.getElementById("record-form").addEventListener("submit", async (e) => {
    e.preventDefault();
    const errorEl = document.getElementById("panel-error");
    errorEl.textContent = "";
    try {
      const data = readForm(entity);
      if (EDITING_ID != null) {
        await api("/" + entity.name + "/" + EDITING_ID, { method: "PATCH", body: JSON.stringify(data) });
        EDITING_ID = null;
      } else {
        await api("/" + entity.name, { method: "POST", body: JSON.stringify(data) });
      }
      await renderPanel(entity);
    } catch (err) {
      errorEl.textContent = err.message;
    }
  });

  await loadRecords(entity);
}

async function loadRecords(entity) {
  const holder = document.getElementById("table-holder");
  holder.innerHTML = '<p class="muted">Loading…</p>';
  try {
    const { records } = await api("/" + entity.name);
    if (records.length === 0) {
      holder.innerHTML = '<p class="muted">No records yet.</p>';
      return;
    }
    const headerHtml = entity.fields.map((f) => '<th>' + f.label + '</th>').join("") + "<th></th>";
    const rowsHtml = records.map((r) => {
      const cells = entity.fields.map((f) => '<td>' + formatCell(f, r[f.name]) + '</td>').join("");
      return '<tr>' + cells + '<td class="row-actions">' +
        '<button data-edit="' + r.id + '">Edit</button>' +
        '<button data-delete="' + r.id + '">Delete</button></td></tr>';
    }).join("");
    holder.innerHTML = '<div class="table-scroll"><table><thead><tr>' + headerHtml + '</tr></thead><tbody>' + rowsHtml + '</tbody></table></div>';

    holder.querySelectorAll("[data-edit]").forEach((btn) => {
      btn.addEventListener("click", async () => {
        const id = Number(btn.getAttribute("data-edit"));
        const record = records.find((r) => r.id === id);
        EDITING_ID = id;
        for (const f of entity.fields) {
          const el = document.getElementById("f_" + entity.name + "_" + f.name);
          if (f.type === "boolean") el.checked = Boolean(record[f.name]);
          else el.value = record[f.name] ?? "";
        }
        document.getElementById("submit-btn").textContent = "Save";
        document.getElementById("cancel-btn").style.display = "inline-block";
        document.getElementById("cancel-btn").onclick = () => renderPanel(entity);
      });
    });
    holder.querySelectorAll("[data-delete]").forEach((btn) => {
      btn.addEventListener("click", async () => {
        await api("/" + entity.name + "/" + btn.getAttribute("data-delete"), { method: "DELETE" });
        await loadRecords(entity);
      });
    });
  } catch (err) {
    holder.innerHTML = '<p class="error">' + err.message + '</p>';
  }
}

async function boot() {
  const { entities } = await api("/entities");
  ENTITIES = entities;
  const tabs = document.getElementById("tabs");
  tabs.innerHTML = ENTITIES.map((e) => '<button data-tab="' + e.name + '">' + e.label + '</button>').join("");
  tabs.querySelectorAll("button").forEach((btn) => {
    btn.addEventListener("click", () => selectTab(btn.getAttribute("data-tab")));
  });
  if (ENTITIES.length > 0) selectTab(ENTITIES[0].name);
}

function selectTab(name) {
  ACTIVE = ENTITIES.find((e) => e.name === name);
  EDITING_ID = null;
  document.querySelectorAll("#tabs button").forEach((b) => {
    b.classList.toggle("active", b.getAttribute("data-tab") === name);
  });
  renderPanel(ACTIVE);
}

boot();
</script>
</body>
</html>
`;
}

export function generateExportFiles(project: Project): { path: string; content: string }[] {
  return [
    { path: "package.json", content: renderPackageJson(project) },
    { path: "README.md", content: renderReadme(project) },
    { path: "server.js", content: renderServerJs(project) },
    { path: "public/index.html", content: renderIndexHtml(project) },
    { path: ".gitignore", content: "node_modules/\ndata.sqlite\n" },
  ];
}
